# Make it possible to switch adapters by passing the ACTION_CABLE_ADAPTER env variable.
# For example, you can use it fallback to the standard Action Cable in staging/review
# environments (by setting `ACTION_CABLE_ADAPTER=redis`).
development:
  #adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>
  adapter: 'any_cable'

test:
  adapter: 'any_cable'

production:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>
